Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.network "forwarded_port", guest: 80, host: 8090
    config.vm.network "public_network", ip: "192.168.15.55"
    config.vm.provider "virtualbox" do |vb|
    config.vm.boot_timeout = 600
    config.vm.provision "shell", inline: <<-SHELL
    chmod +x /vagrant/provision.sh
      /vagrant/provision.sh
    SHELL
      vb.memory = "1024"
      vb.cpus = 2
    end
  end