Vagrant.configure("2") do |config|
    # Configurações da máquina virtual
    config.vm.box = "ubuntu/focal64"
    config.vm.network "public_network", bridge: "eth0"
    config.vm.synced_folder ".", "/vagrant_data"
  
    # Configurações de hardware
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  
    # Configurações do sistema operacional
    config.vm.hostname = "Ubuntu"
  end